# Generated by Django 4.2.2 on 2023-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
