# Generated by Django 4.2.2 on 2023-07-02 21:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('arabic', 'Arabic'), ('hindi', 'Hindi'), ('urdu', 'Urdu')], default='bangla', max_length=100),
        ),
    ]
